### ISSUE TITLE
Image for CIO page

### ISSUE THREAD

**Issue by Katsmi60** [clirdlf/clir_theme#76] opened 2017-09-26 15:24 UTC
I see that the blackboard image has been put into the CIOs page -- but it's appearing as a narrow banner rather than the bigger one I thought we'd be using for program landing pages. Did I misunderstand something, or are you still working on that page?

**Comment by waynegraham** [comment] 2017-09-26 18:57
Dupe of #75 (isn't closed)

**Closed by waynegraham** 2017-09-26 18:57 UTC
